version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: '00:00'
      timezone: Etc/UTC
    groups:
      workflow-dependencies:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: '00:00'
      timezone: Etc/UTC
    groups:
      maven-dependencies:
        patterns:
          - "*"
