name: 🧩 CI · Common Build

on:
  workflow_call:
    inputs:
      ref:
        required: false
        default: ''
        type: string
      release:
        required: false
        default: false
        type: boolean
    outputs:
      commit_sha:
        description: Commit SHA.
        value: ${{ jobs.build.outputs.commit_sha }}
      version:
        description: Version.
        value: ${{ jobs.build.outputs.version }}
  workflow_dispatch:
    inputs:
      ref:
        description: Ref.
        required: false
        default: ''
        type: string
      release:
        description: Release.
        required: true
        default: false
        type: boolean

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_build_common.yml@500889119b97ea2fdea9c2d8b4419abab56c68d0
    with:
      ref: ${{ inputs.ref || github.sha }}
      release: ${{ inputs.release }}
