name: 🔄 CD · Snapshot

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      maven_central:
        description: Maven Central.
        required: true
        default: true
        type: boolean
      github_packages:
        description: GitHub Packages.
        required: true
        default: true
        type: boolean

permissions: {}

concurrency:
  group: build-main-${{ github.ref || github.run_id }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_release.yml@2a85cb9f1adf681086cff8d14427c898ca2e923a
    with:
      semver_strategy: snapshot

  central:
    needs:
      - release
    if: ${{ always() && !cancelled() && needs.release.result == 'success' }}
    permissions:
      actions: read
      contents: read
      deployments: write
    uses: ./.github/workflows/publish-central.yml
    with:
      dry_run: ${{ (github.event_name != 'push' && inputs.maven_central != true) || needs.release.outputs.dry_run == 'true' }}
    secrets:
      CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
      CENTRAL_PASS: ${{ secrets.CENTRAL_PASS }}
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  packages:
    needs:
      - release
    if: ${{ always() && !cancelled() && needs.release.result == 'success' }}
    permissions:
      actions: read
      contents: read
      deployments: write
      packages: write
    uses: ./.github/workflows/publish-github-packages.yml
    with:
      dry_run: ${{ (github.event_name != 'push' && inputs.github_packages != true) || needs.release.outputs.dry_run == 'true' }}
