name: 🧩 CI · Common Build

on:
  workflow_call:
    inputs:
      ref:
        required: false
        default: ''
        type: string
      upload_artifact:
        required: false
        default: false
        type: boolean
    outputs:
      commit_sha:
        description: Commit SHA.
        value: ${{ jobs.build.outputs.commit_sha }}
      version:
        description: Version.
        value: ${{ jobs.build.outputs.version }}
  workflow_dispatch:
    inputs:
      ref:
        description: Ref.
        required: false
        default: ''
        type: string
      upload_artifact:
        description: Upload artifact.
        required: true
        default: false
        type: boolean

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_build_common.yml@df93fbaf3b2026272d2eff4a1794ec175f99d466
    with:
      ref: ${{ inputs.ref || github.sha }}
      upload_artifact: ${{ inputs.upload_artifact }}
