name: Daily

on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/release.yml
    with:
      maven_central: false
      github_packages: false
      force: true
    secrets: inherit
