name: 📦 CD · Publish GitHub Packages

on:
  workflow_call:
    inputs:
      run_id:
        description: Build run.
        required: false
        default: ''
        type: string
      dry_run:
        description: Validate without deploy.
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      run_id:
        description: Build run.
        required: true
        type: string
      dry_run:
        description: Dry run.
        required: true
        default: false
        type: boolean

permissions: {}

jobs:
  publish:
    permissions:
      actions: read
      contents: read
      deployments: write
      packages: write
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_publish_github_packages.yml@7c007762613a9770e3271902fea20d12fa68d1bf
    with:
      run_id: ${{ inputs.run_id }}
      dry_run: ${{ inputs.dry_run }}
