# yuna-java-release: true
name: 🏷️ CD · Release

on:
  workflow_call:
    inputs:
      maven_central:
        description: Maven Central.
        required: false
        default: true
        type: boolean
      github_packages:
        description: GitHub Packages.
        required: false
        default: true
        type: boolean
      force:
        description: Publish unchanged source.
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      maven_central:
        description: Maven Central.
        required: true
        default: true
        type: boolean
      github_packages:
        description: GitHub Packages.
        required: true
        default: true
        type: boolean
      force:
        description: Force.
        required: true
        default: false
        type: boolean

permissions: {}

jobs:
  release:
    permissions:
      contents: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_release.yml@3823e7c3068ee244b07370bef2a2c19942c9bc18
    with:
      force: ${{ inputs.force }}

  central:
    needs:
      - release
    if: ${{ always() && !cancelled() && needs.release.result == 'success' }}
    permissions:
      actions: read
      contents: read
      deployments: write
    uses: ./.github/workflows/publish-central.yml
    with:
      dry_run: ${{ inputs.maven_central != true || needs.release.outputs.dry_run == 'true' }}
    secrets:
      CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
      CENTRAL_PASS: ${{ secrets.CENTRAL_PASS }}
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  packages:
    needs:
      - release
    if: ${{ always() && !cancelled() && needs.release.result == 'success' }}
    permissions:
      actions: read
      contents: read
      deployments: write
      packages: write
    uses: ./.github/workflows/publish-github-packages.yml
    with:
      dry_run: ${{ inputs.github_packages != true || needs.release.outputs.dry_run == 'true' }}

  github:
    needs:
      - release
      - central
      - packages
    if: ${{ always() && !cancelled() && needs.release.outputs.dry_run == 'false' && !endsWith(needs.release.outputs.version, '-SNAPSHOT') && needs.release.result == 'success' && needs.central.result == 'success' && needs.packages.result == 'success' }}
    permissions:
      actions: read
      contents: write
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_create_github_release.yml@3823e7c3068ee244b07370bef2a2c19942c9bc18
    with:
      commit_sha: ${{ needs.release.outputs.commit_sha }}
      version: ${{ needs.release.outputs.version }}
